### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by PengpengGuan** [smithlabcode/abismal#16]
Hello, when I install the abismal-3.0.0, there are some errors.
I install abismal in the linux.

The part of error information is as follows:
![QQ图片20221011101600](https://user-images.githubusercontent.com/23093342/194982099-6544ef7e-81fc-4e5a-ac36-103749737685.png)

make[3]: Entering directory '/public/home/ppguan/soft/Abismal/abismal-3.0.0/src/smithlab_cpp'
g++ -std=c++11 -DHAVE_CONFIG_H -I.     -O3 -MT OptionParser.o -MD -MP -MF .deps/OptionParser.Tpo -c -o OptionParser.o OptionParser.cpp
OptionParser.cpp: In function ?.oid read_config_file(const string&, std::vector<std::basic_string<char> >&)?.
OptionParser.cpp:371:54: error: no matching function for call to ?.egex_replace(std::string&, std::regex, const char [1])?
     line = regex_replace(line, regex(outer_space), "");
                                                      ^

could you help me to solve it? Thanks you

**Comment by guilhermesena1** [comment]
Hello,

Thank you for reporting the issue.

We are aware that regex in smithlab_cpp is causing various compilation issues across software tools and we will replace its functionality with equivalent functions that don't use this library.

Normally this happens when your g++ version is the default one that ships with ubuntu. For the program to compile there are two solutions, none of which are ideal but both of which work without problems

**Solution 1: Update your g++**
On ubuntu you can do this with
```
sudo apt install gcc-10
```

and probably also with
```
sudo apt install build-essential
```

**Solution 2: Delete the regex code**
You can also just delete the following lines from the file `src/smithlab_cpp/OptionParser.cpp`:
 * Line 35 that says `include <regex>`
 * Line 44 that says `using std::regex`
 * Line 371 that says `line = regex_replace(line, regex(outer_space), "");`
 * Line 372 that says `line = regex_replace(line, regex(inner_space), " ");`
 * Line 389 that says `option_value = regex_replace(line, regex(outer_space), "");`

Then the program should compile and run without issues (I promise this won't break anything in functionality)

Also if I may suggest: You might consider using the most recent release, version 3.1.1, instead of 3.0.0. No harm in using more recent code :)

Please let me know if any of this helps compile and run the program!

**Comment by PengpengGuan** [comment]
Thank you give me the soluation to solve this problem.
I have installed this soft successfully according to the soluation2 that you provied. 
Thanks again

**Comment by andrewdavidsmith** [comment]
@PengpengGuan Great! I think that same solution has now been built into more recent releases. If you bump into the same issue again let us know so we can check on it.
