### ISSUE TITLE
Reference genome, soft masked or hard mask

### ISSUE THREAD

**Issue by moqri** [smithlabcode/abismal#26]
Thanks again for your great package! 

Question: 

Is there any recommendation for using the the soft masked or hard masked version of the reference genome for indexing and how that might affects the mapping quality/speed?

**Comment by andrewdavidsmith** [comment]
I suspect the hard masked might lead to speed improvements, but wouldn't be worth it because the criteria typically used for masking are way too relaxed and mean you will lose too much information.

I will test this, to know about the speed issue, but I am very confident you'd lose too much information that way.

**Comment by andrewdavidsmith** [comment]
This issue has been addressed with the inclusion of target regions when indexing in v3.2.2 (PR #43).
