### ISSUE TITLE
Continued trailing space error

### ISSUE THREAD

**Issue by SDeans0** [smithlabcode/abismal#3]
First, thanks for releasing another tool, the results look very promising in the biorxiv paper. 

I mapped some reads with abismal on Friday, having installed it from the master branch. I was unable to extract methylation either with MethylDackel or the pipeline from the paper; the former had a faidx searching error, and the latter turned all of the mapping locations to * after the format_reads step and gave an error saying that each read belonged to an unknown chromosome. 

I think that the problem is with the abismal output having a trailing space after the chromosome name, as in issue #2. When I replaced the spaces/tabs with the letter s with sed, I could see that there was still a trailing space after the sequence name in both the header and the lines for each sequence. I removed the double space using ````samtools view test.bam -h | sed 's/\s\s/\t/g' | samtools view -bh > test_fixed.bam```` and the downstream steps worked, confirming that this is the source of the problem.

I've taken to adding the sed command straight after the mapping step which works fine, but it would be great to have a bugfix for this.

**Comment by guilhermesena1** [comment]
Hi Sam,

Thank you so much for reporting this bug and for the thorough search for the potential causes of error, it made it much easier to reproduce the problem.

I'm assuming the chromosome names in your FASTA file have spaces? (e.g. `>chr1 some metadata here` as opposed to just `>chr1`). You're absolutely right that this issue is the same as #2, which caused this error on FASTQ reads whose names have spaces, and the fix was also similar (but for the FASTA not the FASTQ). I pushed a change that, hopefully, upon recompilation, will solve the problem. Unfortunately, resolving this problem means that your genome will have to be re-indexed, as the chromosome names saved in the index file contain whitespaces. I hope this is not too much of a problem.

Out of curiosity, this problem could also be bypassed on the previous "broken" commit of abismal by making a non-whitespace reference genome (e.g. `awk '{print $1}' genome.fa >genome_no_whitespaces.fa`).

If you attempt to pull the fix and re-run abismal in your data, I'd be extremely grateful if you could let us know if it fixes the problem. Thank you very much in advance!

**Comment by SDeans0** [comment]
Hi Guilherme,

Thanks for the swift bugfix - I recompiled it and can confirm that it works! You were right that it came from the fasta file having metadata following a space. I'll tell you if I spot anything else surprising.

Sam
